### PR TITLE
Improved grammar and fixed capitalization in the bio and at the bottom of the work page

### PR DESCRIPTION
**Pull request by rajpiskala**
Note: Neither VS code or I could find the descriptions for the project page. From running it locally, it's clear that it's there, but I'm assuming the text is stored somewhere else as I can't find it in the project repository.

### CODE REVIEW

**Comment by rajpiskala** [comment]
@anthonwellsjo Do you mind either rejecting or approving this pull request?

**Comment by anthonwellsjo** [comment]
Sorry im gonna go through it soon. In the middle of a house move so everythings on hold.

**Comment by anthonwellsjo** [comment]
Hey RogueArt, I really appreciate your effort. My only problem is that you are over writing a lot of files (e.g. the json.lock file) so if you can make a new PR for only those files that you are editing I'm gonna go ahead and merge.

Thansk again!

**Comment by rajpiskala** [comment]
Yep, just noticed that. I'll make a new pull request with the two files I changed.

**Comment by anthonwellsjo** [comment]
Hey Rogue,

my projects lives on Sanity CMS and I'm hesitant on letting you access there. However i'm really appreciating your help. Following you now on Github. Would love to work together on something some time. Best regards

**Comment by rajpiskala** [comment]
Thanks for the follow! I've made a Gist [here](https://gist.github.com/RogueArt/a49ff77b3df3867d48e58073a71aad22) with changes to the three project descriptions as well. Hope that helps and I'll hit you up sometime soon if I have any cool projects I want to work on!

**Pull request closed without merging**
